name: CI

on:[push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Build
      run: docker build -t christianmoesl/wasmdb-backend .
    
    - name: Test
      run: docker run christianmoesl/wasmdb-backend sbt test
      
    - name: Update DockerHub Image
      if: github.ref == 'refs/heads/wasmdb'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u christianmoesl --password-stdin
        docker push christianmoesl/lms-wasm
    
    - name: Deploy assembly as AWS Lambda Function
      if: github.ref == 'refs/heads/wasmdb'
      run: |
        docker build -t deploy -f Dockerfile_deploy .
        docker run -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                   -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                   -e AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }} deploy
