name: Release

on:
  push:
    branches:
    - wasmdb

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: docker build -t christianmoesl/wasmdb-backend .

    - name: Update DockerHub Image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u christianmoesl --password-stdin
        docker push christianmoesl/wasmdb-backend

    - name: Deploy assembly as AWS Lambda Function
      run: |
        docker build -t deploy -f Dockerfile_deploy .
        docker run -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                   -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                   -e AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }} deploy
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u christianmoesl --password-stdin
        docker push christianmoesl/wasmdb-backend:deploy-latest
